### ISSUE TITLE
plot sensors on picture

### ISSUE THREAD

**Issue by gneeser** [puhep/pudb2#12]
Eventually, I'd like to automatically generate a picture for each test which shows the location of each element on the support structure, whether the object be a sensor, heater, or mock module.

To do this, I'll need an official background to begin with each time, and I'll also need to know the scale of the support structures. If this will change from structure to structure, then it quickly becomes much more complicated, but the situation could be remedied if the number of structures is kept low and we changed the background pic for each structure.

**Comment by gneeser** [comment]
Sensors are now automatically plotted on upload, but I still need a scale for the support structures and a background image.

**Comment by AndySpring** [comment]
Since the inlet and outlet do not have positions as defined in our graph, could you make them in a default position or just have the system ignore the sensor if no x or y values are given? Now we cant see the graph of the sensors because T10 and T11 do not have positions.

![position error](https://cloud.githubusercontent.com/assets/26171360/23719416/485bdd56-0409-11e7-8197-561512caafbd.PNG)

**Comment by gneeser** [comment]
Ah, yes, I can do that. I should have done that in the first place. I'll let you know when I push out the change.

**Comment by gneeser** [comment]
Empty values are now ignored. Also note that I have hardcoded the graph to be 15x15 cm with the origin at the bottom left-hand corner as per @NickHinton's request, so the plot will not show negative values. I can change this if need be.

**Comment by gneeser** [comment]
Also, I can hard-code some objects such as the inlet and outlet if you would like. Just let me know where and what you want them to look like

**Comment by NickHinton** [comment]
Inlet and outlet default positions would be nice. [7.5,17] and [7.5,-2].
